# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cobject.proto\x12\x0ejsonvsprotobuf\"\x81\x01\n\x06Object\x12\x11\n\tobject_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\ntime_start\x18\x04 \x01(\t\x12\x10\n\x08time_end\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\x02\x12\x0b\n\x03url\x18\x07 \x01(\t\"5\n\nObjectColl\x12\'\n\x07objects\x18\x01 \x03(\x0b\x32\x16.jsonvsprotobuf.Objectb\x06proto3')



_OBJECT = DESCRIPTOR.message_types_by_name['Object']
_OBJECTCOLL = DESCRIPTOR.message_types_by_name['ObjectColl']
Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), {
  'DESCRIPTOR' : _OBJECT,
  '__module__' : 'object_pb2'
  # @@protoc_insertion_point(class_scope:jsonvsprotobuf.Object)
  })
_sym_db.RegisterMessage(Object)

ObjectColl = _reflection.GeneratedProtocolMessageType('ObjectColl', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTCOLL,
  '__module__' : 'object_pb2'
  # @@protoc_insertion_point(class_scope:jsonvsprotobuf.ObjectColl)
  })
_sym_db.RegisterMessage(ObjectColl)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBJECT._serialized_start=33
  _OBJECT._serialized_end=162
  _OBJECTCOLL._serialized_start=164
  _OBJECTCOLL._serialized_end=217
# @@protoc_insertion_point(module_scope)
