# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: object.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'object.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cobject.proto\x12\x0ejsonvsprotobuf\"\x81\x01\n\x06Object\x12\x11\n\tobject_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\ntime_start\x18\x04 \x01(\t\x12\x10\n\x08time_end\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\x02\x12\x0b\n\x03url\x18\x07 \x01(\t\"5\n\nObjectColl\x12\'\n\x07objects\x18\x01 \x03(\x0b\x32\x16.jsonvsprotobuf.Object\"2\n\x0eObjectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2U\n\rObjectService\x12\x44\n\nSendObject\x12\x16.jsonvsprotobuf.Object\x1a\x1e.jsonvsprotobuf.ObjectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'object_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECT']._serialized_start=33
  _globals['_OBJECT']._serialized_end=162
  _globals['_OBJECTCOLL']._serialized_start=164
  _globals['_OBJECTCOLL']._serialized_end=217
  _globals['_OBJECTRESPONSE']._serialized_start=219
  _globals['_OBJECTRESPONSE']._serialized_end=269
  _globals['_OBJECTSERVICE']._serialized_start=271
  _globals['_OBJECTSERVICE']._serialized_end=356
# @@protoc_insertion_point(module_scope)
